name: Deploy to Ubuntu VM (CI/CD)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.1.192 >> ~/.ssh/known_hosts

      - name: Deploy to Ubuntu VM
        run: |
          ssh -i ~/.ssh/id_rsa user@192.168.1.192 '
          cd ~/registry-devops &&
          git pull &&
          docker compose down &&
          docker compose up --build -d
          '
